### ISSUE TITLE
Rails 3.2 里面开发环境开启 cache 以后，如果代码有修改，Rails 自动重载将会出现  undefined class/module User 的错误

### ISSUE THREAD

**Issue by huacnlee** [flyerhzm/simple_cacheable#5]
这个问题每次都会出现，奇怪的是产品环境却没有问题

比如

``` ruby
class Topic < ActiveRecord::Base
  model_cache do
    with_association :user, :group
  end
end
```

当我页面上有调用 `@topic.cached_user` 或 `@topic.cached_group` 的时候

**如果这个时候，我修改了任意一个 Models 里面的文件，再次刷新的时候，就会出现**

``` ruby
undefined class/module Group
或
undefined class/module User
```

清除  memcached 的缓存或者重启 rails server 以后就能回复正常，在次继续刷新也不会有问题

错误详细:

```
activesupport (3.2.3) lib/active_support/cache.rb:587:in `load'
activesupport (3.2.3) lib/active_support/cache.rb:587:in `value'
activesupport (3.2.3) lib/active_support/cache.rb:294:in `fetch'
(eval):2:in `cached_group'
app/views/home/index.html.erb:80:in `block in _app_views_home_index_html_erb__2655772757043789158_70187875347500'
app/views/home/index.html.erb:77:in `each'
app/views/home/index.html.erb:77:in `_app_views_home_index_html_erb__2655772757043789158_70187875347500'

... 下面是 View 之类的跟踪
```

**Comment by huacnlee** [comment]
当我加上这个以后问题没了 http://stackoverflow.com/a/5323806

**Comment by flyerhzm** [comment]
嗯，这个应该是cache store的职责，超出了simple_cacheable应该处理的范畴
